let lessons = {
    beginning: {
        middleRow: {
        text:
            ["aa ss dd ff jj kk ll ;;",
            "as as df df jk jk l; l;",
            "as as df df jk jk l; l;",
            "sa sa fd fd kj kj ;l ;l",
            "jkl; jkl; asdf asdf",
            "fdsa fdsa ;lkj ;lkj",
            "asdf asdf jkl; jkl;"],
        settings: {
            keyboardBacklight: true,
            keyboardHands: true,
            showKeyboard: true,
        }
        },
        newKeys1:
        ["ad ad jk jk ad ad jk jk",
        "jljl adad jljl adad",
        "sfsf adad jljl sfsf",
        "fsfs dada ljlj fsfs",
        "fsfs adad jllj sffs",
        "jkfd dfkj kjdf fdjk",
        "affa j;;j jkfd l;sa",
        "afds j;lk jkj; ;jad"],
        newKeys2:
        ["adfs adfs jlk; jlk;",
        "ajsk ajsk ;lfd ;lfd",
        "afsd afsd j;kl j;kl",
        "jfa; jfa; ;afj ;afj",
        "slsl kdkd jfjf ;a;a",
        "akak sjsj dkdk alal",
        "aslk dfkj aslk dfkj",
        "fjkd fkjd fkjd fjkd",
        "a;ls ls;a ;jlk j;lk",
        "f;a; ja;a ks;a ;ajs"],
        newKeys3:
        ["lsda lfds jfal jfal",
        "laks skda sdas alla",
        "fsls slfk slfk fsls",
        "alsk alsk ddak ddaj",
        "aj;; jka; ;jka ;;ja",
        "fja; fja; akdl aks;",
        "aslk dfkj aslk askj",
        "fjkl a;sl sla; fl;s",
        "fsl; ;als jfkd jfkd",
        "ajsl l;al asjd ajdk"],
        keyTest1:
        ["ask ask ask ask",
        "add add add add",
        "dad dad dad dad",
        "fas fas fas fas",
        "dsd dsd dsd dsd",
        "lkj lkj lkj lkj",
        "fad fad fad fad",
        "all all all all",
        "ala ala ala ala",
        "sad sad sad sad",
        "flak flak flak flak",
        "flask flask flask flask",
        "fall fall fall fall",
        "alas alas alas alas",
        "salad salad salad salad",
        "alfala alfala alfala aflala",
        "sals sals sals sals sals"],
        wordTest1:
        ["all ask fall ask",
        "dad ask fall adds",
        "adds salad flask all",
        "daff all salad salsa",
        "sals; flack; ;slak dad",
        "asks salad; fall sad",
        "alfa ;alfa salad falls",
        "allas all sad; ask fad;",
        "all fads fad salsa;",
        "las; salad allas sals",
        "alas daff flask fask",
        "sass lad lads fask",
        "as salsa las; alas",
        "adds fads lass sass",
        "adj adk all sad adds",
        "asks falls dad all",
        "laff daffs alls sass"],
    }
}